import food1 from "../assets/images/Card/food1.png";
import food2 from "../assets/images/Card/food2.png";
import food3 from "../assets/images/Card/food3.png";
import food4 from "../assets/images/Card/food4.png";
import food5 from "../assets/images/Card/food5.png";
import food6 from "../assets/images/Card/food6.png";
import food7 from "../assets/images/Card/food7.png";
import food8 from "../assets/images/Card/food8.png";

export const datas = [
    {
        id: 1,
        img: food1,
        title: "Slim",
        kcal: [1000, 1300, 1500],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 57,
        tags: ["Breakfast", "Snacks"],
    },
    {
        id: 2,
        img: food2,
        title: "Fit",
        kcal: [1800, 2000, 2500],
        desc: "Taque earum rerum hic tenetur a sapiente maiores ...",
        price: 65,
        tags: ["Breakfast", "Lunch"],
    },
    {
        id: 3,
        img: food3,
        title: "Vegan",
        kcal: [1300, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 59,
        tags: ["II Breakfast", "Lunch"],
    },
    {
        id: 4,
        img: food4,
        title: "Keto",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["Breakfast", "II Breakfast"],
    },
    {
        id: 5,
        img: food5,
        title: "Gym",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["II Breakfast", "Lunch"],
    },
    {
        id: 6,
        img: food6,
        title: "Office box",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["Breakfast", "Lunch"],
    },
    {
        id: 7,
        img: food7,
        title: "For moms",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["Breakfast", "II Breakfast", "Dinner"],
    },
    {
        id: 8,
        img: food8,
        title: "Low IG",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["Breakfast", "Dinner"],
    },
    {
        id: 9,
        img: food1,
        title: "Slim",
        kcal: [1000, 1300, 1500],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 57,
        tags: ["Breakfast", "II Breakfast"],
    },
    {
        id: 10,
        img: food2,
        title: "Fit",
        kcal: [1800, 2000, 2500],
        desc: "Taque earum rerum hic tenetur a sapiente maiores ...",
        price: 65,
        tags: ["Breakfast", "II Breakfast"],
    },
    {
        id: 11,
        img: food3,
        title: "Vegan",
        kcal: [1300, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 59,
        tags: ["Breakfast", "II Breakfast"],
    },
    {
        id: 12,
        img: food4,
        title: "Keto",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["Breakfast", "Dinner"],
    },
    {
        id: 13,
        img: food5,
        title: "Gym",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["Lunch", "II Breakfast", "Snacks"],
    },
    {
        id: 14,
        img: food6,
        title: "Office box",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["Lunch", "Dinner"],
    },
    {
        id: 15,
        img: food7,
        title: "For moms",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 62,
        tags: ["Breakfast", "Snacks"],
    },
    {
        id: 16,
        img: food8,
        title: "Low IG",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 100,
        tags: ["Lunch", "Dinner", "Snacks"],
    },
    {
        id: 17,
        img: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80",
        title: "Office box",
        kcal: [1200, 1500, 2000],
        desc: "Taque earum rerum hic tenetur a sapiente maiores alias consequatur aut perferendis doloribus asperiores...",
        price: 100,
        tags: ["Lunch", "Dinner", "Snacks"],
    },
];
